apiVersion: v2
name: pagopa-observability-bdi
description: Microservice description
type: application
version: 0.87.0
appVersion: 0.9.16
dependencies:
  - name: microservice-chart
    version: 7.5.0
    alias: pagopa-observability-bdi
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
