apiVersion: v2
name: pagopa-observability-bdi
description: Microservice description
type: application
version: 0.85.0
appVersion: 0.9.14
dependencies:
  - name: microservice-chart
    version: 7.5.0
    alias: pagopa-observability-bdi
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
