apiVersion: v2
name: pagopa-observability-bdi
description: Collecting performance data about pagoPA platform
type: application
version: 0.97.0
appVersion: 0.9.26
dependencies:
  - name: microservice-chart
    version: 8.0.2
    alias: pagopa-observability-bdi
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
