apiVersion: v2
name: pagopa-observability-bdi
description: Collecting performance data about pagoPA platform
type: application
version: 0.89.0
appVersion: 0.9.18
dependencies:
  - name: microservice-chart
    version: 7.5.0
    alias: pagopa-observability-bdi
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
